[edge_gateway]
oracle-edge ansible_host=192.168.8.2 ansible_user=leoleidenoracle2

[edge_gateway:vars]
ansible_python_interpreter=/usr/bin/python3
# Вимикаємо перевірку SSH-ключа для спрощення тестування у віртуальному середовищі
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
